#!/bin/bash
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# https://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &
xmodmap ~/.xmodmap
setxkbmap -option "ctrl:nocaps" &

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# Set off xscreensaver
xscreensaver & disown

# Try out a hack for DBUS session etc
export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"

# Set a wallpaper
nitrogen --restore

# Start the system tray
stalonetray -c ~/.xmonad/stalonetrayrc-single &

# Start sound server
pulseaudio --start --log-target=syslog &

exec dbus-launch --sh-syntax --exit-with-session xmonad
