#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# https://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &
xmodmap ~/.xmodmap
setxkbmap -option "ctrl:nocaps" &

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# Monitor geometry
xrandr --output eDP-1 --below DP-1

# Set a wallpaper
feh --bg-fill ~/misc/desktop_backgrounds/ubuntu_desktop_blue-wallpaper-1920x1080.jpg

# Start the system tray
stalonetray -c ~/.xmonad/stalonetrayrc-single &

# Start sound server
pulseaudio --start --log-target=syslog &

exec ck-launch-session dbus-launch --sh-syntax --exit-with-session xmonad
